#!/bin/sh -e
# Copyright (c) 2013 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.
REQUIRES='lxde'
DESCRIPTION='Installs the Lubuntu desktop distribution (Approx. 800MB)'
HOSTBIN='startdm'
. "${TARGETSDIR:="$PWD"}/common"

### Append to prepare.sh:
apt-get -y install lubuntu-desktop `noauto chromium-browser network-manager`

TIPS="$TIPS
You can start Lubuntu via the startdm host command: sudo startdm
"
