#!/bin/sh -e
# Copyright (c) 2013 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.
REQUIRES='xfce'
DESCRIPTION='Installs the Xubuntu desktop distribution (Approx. 1200MB)'
HOSTBIN='startdm'
. "${TARGETSDIR:="$PWD"}/common"

### Append to prepare.sh:
apt-get -y install xubuntu-desktop `noauto firefox network-manager xorg`

TIPS="$TIPS
You can start Xubuntu via the startdm host command: sudo startdm
"
